bizzfuzz/urls.py
from django.conf.urls import url
from . import views
from .views import BuzzListView, BuzzDetailView, BuzzCreateView, BuzzDeleteView, BuzzUpdateView

app_name = 'bizzfuzz'

urlpatterns = [
    url(r'^$', BuzzListView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', BuzzDetailView.as_view(), name='detail'),
    url(r'^create/$', BuzzCreateView.as_view(), name='create'),
    url(r'^delete/(?P<pk>\d+)/$', BuzzDeleteView.as_view(), name='delete'),
    url(r'^edit/(?P<pk>\d+)/$', BuzzUpdateView.as_view(), name='edit'),
    url(r'^exportcsv/', views.ExportProfilesCsvView.as_view(), name='export'),
]

buzzfuzz/urls.py
from django.conf.urls import url
from . import views
from .views import BuzzListView, BuzzDetailView, BuzzCreateView, BuzzDeleteView, BuzzUpdateView

app_name = 'buzzfuzz'

urlpatterns = [
    url(r'^$', BuzzListView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', BuzzDetailView.as_view(), name='detail'),
    url(r'^create/$', BuzzCreateView.as_view(), name='create'),
    url(r'^delete/(?P<pk>\d+)/$', BuzzDeleteView.as_view(), name='delete'),
    url(r'^edit/(?P<pk>\d+)/$', BuzzUpdateView.as_view(), name='edit'),
    url(r'^exportcsv/', views.ExportProfilesCsvView.as_view(),  name='export'),
]

prj/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('bizzfuzz.urls')),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bizzfuzz/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core.urlresolvers import reverse


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    birthday = models.DateField(null=True, blank=True)
    random = models.PositiveIntegerField()

    def get_absolute_url(self):
        return reverse('bizzfuzz:detail', kwargs={'pk': self.id})

    def __str__(self):
        return self.user.username

    def delete(self):
        user = self.user
        super(Profile, self).delete()
        user.delete()

buzzfuzz/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core.urlresolvers import reverse


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    birthday = models.DateField(null=True, blank=True)
    random = models.PositiveIntegerField()

    def get_absolute_url(self):
        return reverse('buzzfuzz:detail', kwargs={'pk': self.id})

    def __str__(self):
        return self.user.username

    def delete(self):
        user = self.user
        super(Profile, self).delete()
        user.delete()

bizzfuzz/forms.py
from random import randint
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class ProfileForm(UserCreationForm):
    username = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'placeholder': 'Required. Letters, digits and @/./+/-/_ only.'}))

    password1 = forms.CharField(
        label='Password',
        required=True,
        widget=forms.PasswordInput(attrs={'placeholder': 'Required'}))

    password2 = forms.CharField(
        label='Confirm Password',
        required=True,
        widget=forms.PasswordInput(attrs={'placeholder': 'Enter the same password as before, for verification'}))

    birthday = forms.DateField(
        required=True,
        widget=forms.TextInput(attrs={'placeholder': 'Required. Enter as YYYY-MM-DD'}))

    def save(self, commit=True):
        user = super(ProfileForm, self).save(commit=commit)

        user_profile = Profile.objects.create(
            user=user,
            birthday=self.cleaned_data['birthday'],
            random=randint(1, 100),
        )
        return user_profile

bizzfuzz/views.py
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView, RedirectView

from .models import Profile
from .forms import ProfileForm


class BuzzListView(ListView):
    template_name = 'bizzfuzz/index.html'
    model = Profile


class BuzzRedirectView(RedirectView):
    url = reverse_lazy('index')


class BuzzDetailView(DetailView):
    template_name = 'bizzfuzz/detail.html'
    model = Profile


class BuzzCreateView(CreateView):
    template_name = 'bizzfuzz/create.html'
    form_class = ProfileForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(BuzzCreateView, self).form_valid(form)


class BuzzDeleteView(DeleteView):
    model = Profile
    success_url = reverse_lazy('bizzfuzz:index')


class BuzzUpdateView(UpdateView):
    template_name = 'bizzfuzz/edit.html'
    model = Profile
    fields = ['birthday']


class ExportProfilesView(ListView):
    """
    The standard view for HTML return
    """
    template_name = 'bizzfuzz/index.html'
    model = Profile
    context_object_name = 'profile_list'

    def get_queryset(self):
        return Profile.objects.all


class ExportProfilesCsvView(ExportProfilesView):
    """
    Subclass of previous view, to export a CSV file
    """
    template_name = 'bizzfuzz/profilelist.csv'
    content_type = 'text/csv'

buzzfuzz/views.py
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView, RedirectView

from .models import Profile
from .forms import ProfileForm


class BuzzListView(ListView):
    template_name = 'buzzfuzz/index.html'
    model = Profile


class BuzzRedirectView(RedirectView):
    url = reverse_lazy('index')


class BuzzDetailView(DetailView):
    template_name = 'buzzfuzz/detail.html'
    model = Profile


class BuzzCreateView(CreateView):
    template_name = 'buzzfuzz/create.html'
    form_class = ProfileForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(BuzzCreateView, self).form_valid(form)


class BuzzDeleteView(DeleteView):
    model = Profile
    success_url = reverse_lazy('buzzfuzz:index')


class BuzzUpdateView(UpdateView):
    template_name = 'buzzfuzz/edit.html'
    model = Profile
    fields = ['birthday']


class ExportProfilesView(ListView):
    """
    The standard view for HTML return
    """
    template_name = 'buzzfuzz/index.html'
    model = Profile
    context_object_name = 'profile_list'

    def get_queryset(self):
        return Profile.objects.all


class ExportProfilesCsvView(ExportProfilesView):
    """
    Subclass of previous view, to export a CSV file
    """
    template_name = 'buzzfuzz/profilelist.csv'
    content_type = 'text/csv'

bizzfuzz/templates/bizzfuzz/base.html
{% load staticfiles %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>BizzFuzz * {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css" />
    <link rel="stylesheet" href="{% static 'bizzfuzz/css/app.css' %}" />
  </head>
  <body>
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>

  <script src="//cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js" />
  </body>
</html>

bizzfuzz/templates/bizzfuzz/create.html
{% extends 'bizzfuzz/base.html' %}
{% block title %}Create profile{% endblock %}

{% block content %}
  <h3 class="title">Create new profile</h3>
  <form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input class="btn left" type="submit" value="Create" />
  </form>
  <a class="btn red right" href="{% url 'bizzfuzz:index' %}">Cancel</a>
{% endblock %}

bizzfuzz/templates/bizzfuzz/detail.html
{% extends 'bizzfuzz/base.html' %}
{% load staticfiles profiletags %}
{% block title %}Profile details{% endblock %}

{% block content %}
  <h3 class="title">Profile of {{ profile.user.username }}</h3>
  <a class="btn-flat" href="{% url 'bizzfuzz:index' %}">⇠ Back to list</a>
  <div class="card">
    <div class="card-content">
      <p class="center-align">Name: {{ profile.user.username }}</p>
      <p class="center-align">Birthday: {{ profile.birthday|date:'Y-m-d' }}</p>
      <p class="center-align">Eligible: <b>{% status profile %}</b></p>
      <p class="center-align">Random: {{ profile.random }}</p>
      <p class="center-align">BizzFuzz: {% bizzfuzz profile %}</p>
    </div>
    <div class="card-action">
      <form class="right" method="POST" action="{% url 'bizzfuzz:delete' profile.id %}">{% csrf_token %}
        <input class="btn red" type="submit" value="Delete">
      </form>
      <a class="btn" href="{% url 'bizzfuzz:edit' profile.id %}">Edit profile</a>
    </div>
  </div>
{% endblock %}

bizzfuzz/templates/bizzfuzz/edit.html
{% extends 'bizzfuzz/base.html' %}
{% block title %}Edit profile{% endblock %}

{% block content %}
  <h3 class="title">Update profile of {{profile.user.username}}</h3>
  <form class="card" method="post">
    <div class="card-content">
      {% csrf_token %}
      {{ form.as_p }}
    </div>
    <div class="card-action">
      <input class="btn" type="submit" value="Update" />
      <a class="btn red darken-3 right" href="{{ profile.get_absolute_url }}">Cancel</a>
    </div>
  </form>
{% endblock %}

bizzfuzz/templates/bizzfuzz/index.html
{% extends 'bizzfuzz/base.html' %}
{% load staticfiles profiletags %}
{% block title %}Home{% endblock %}

{% block content %}
  <h3 class="title">All profiles</h3>
  <div class="collection">
    <div class="row">
      <div class="collection-item">
        <div class="col s3 m5">Username</div>
        <div class="col s9 m7">
          <div class="col s3 center-align">Birthday</div>
          <div class="col s3 center-align">Eligible</div>
          <div class="col s3 center-align">Random</div>
          <div class="col s3 center-align">BizzFuzz</div>
        </div>
      </div>
    </div>
    <hr />
    {% for profile in profile_list %}
      <a class="collection-item" href="{% url 'bizzfuzz:detail' profile.id %}">
        <div class="row">
          <div class="col s3 m5">{{ profile.user.username }}</div>
          <div class="col s9 m7 badge">
            <div class="col s3 center-align">{{ profile.birthday|date:'m/d/Y' }}</div>
            <div class="col s3 center-align">{% status profile %}</div>
            <div class="col s3 center-align">{{ profile.random }}</div>
            <div class="col s3 center-align">{% bizzfuzz profile %}</div>
          </div>
        </div>
      </a>
    {% endfor %}
  </div>
  <a class="btn" href="{% url 'bizzfuzz:create' %}">Create profile</a>
  <a class="btn blue darken-1 right" href="{% url 'bizzfuzz:export' %}">Export</a>
{% endblock %}

buzzfuzz/templates/buzzfuzz/base.html
{% load staticfiles %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>BuzzFuzz * {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
    <link rel="stylesheet" href="{% static 'buzzfuzz/css/app.css' %}" />
  </head>
  <body>
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>

  <script src="//cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js" />
  </body>
</html>

buzzfuzz/templates/buzzfuzz/create.html
{% extends 'buzzfuzz/base.html' %}
{% block title %}Create profile{% endblock %}

{% block content %}
  <h3 class="title">Create new profile</h3>
  <form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input class="btn left" type="submit" value="Create" />
  </form>
  <a class="btn red right" href="{% url 'buzzfuzz:index' %}">Cancel</a>
{% endblock %}

buzzfuzz/templates/buzzfuzz/detail.html
{% extends 'buzzfuzz/base.html' %}
{% load staticfiles profiletags %}
{% block title %}Profile details{% endblock %}

{% block content %}
  <h3 class="title">Profile of {{ profile.user.username }}</h3>
  <a class="btn-flat" href="{% url 'buzzfuzz:index' %}">⇠ Back to list</a>
  <div class="card">
    <div class="card-content">
      <p class="center-align">Name: {{ profile.user.username }}</p>
      <p class="center-align">Birthday: {{ profile.birthday|date:'Y-m-d' }}</p>
      <p class="center-align">Eligible: <b>{% status profile %}</b></p>
      <p class="center-align">Random: {{ profile.random }}</p>
      <p class="center-align">BizzFuzz: {% bizzfuzz profile %}</p>
    </div>
    <div class="card-action">
      <form class="right" method="POST" action="{% url 'buzzfuzz:delete' profile.id %}">{% csrf_token %}
        <input class="btn red" type="submit" value="Delete">
      </form>
      <a class="btn" href="{% url 'buzzfuzz:edit' profile.id %}">Edit profile</a>
    </div>
  </div>
{% endblock %}

buzzfuzz/templates/buzzfuzz/edit.html
{% extends 'buzzfuzz/base.html' %}
{% block title %}Edit profile{% endblock %}

{% block content %}
  <h3 class="title">Update profile of {{profile.user.username}}</h3>
  <form class="card" method="post">
    <div class="card-content">
      {% csrf_token %}
      {{ form.as_p }}
    </div>
    <div class="card-action">
      <input class="btn" type="submit" value="Update" />
      <a class="btn red darken-3 right" href="{{ profile.get_absolute_url }}">Cancel</a>
    </div>
  </form>
{% endblock %}

buzzfuzz/templates/buzzfuzz/index.html
{% extends 'buzzfuzz/base.html' %}
{% load staticfiles profiletags %}
{% block title %}Home{% endblock %}

{% block content %}
  <h3 class="title">All profiles</h3>
  <div class="collection">
    <div class="row">
      <div class="collection-item">
        <div class="col s3 m5">Username</div>
        <div class="col s9 m7">
          <div class="col s3 center-align">Birthday</div>
          <div class="col s3 center-align">Eligible</div>
          <div class="col s3 center-align">Random</div>
          <div class="col s3 center-align">BizzFuzz</div>
        </div>
      </div>
    </div>
    <hr />
    {% for profile in profile_list %}
      <a class="collection-item" href="{% url 'buzzfuzz:detail' profile.id %}">
        <div class="row">
          <div class="col s3 m5">
            {{ profile.user.username }}
          </div>
          <div class="col s9 m7 badge">
            <div class="col s3 center-align">
              <span>{{ profile.birthday|date:'m/d/Y' }}</span>
            </div>
            <div class="col s3 center-align">
              <span>{% status profile %}</span>
            </div>
            <div class="col s3 center-align">
              <span>{{ profile.random }}</span>
            </div>
            <div class="col s3 center-align">
              <span>{% bizzfuzz profile %}</span>
            </div>
          </div>
        </div>
      </a>
    {% endfor %}
  </div>
  <a class="btn" href="{% url 'buzzfuzz:create' %}">Create profile</a>
  <a class="btn blue darken-1 right" href="{% url 'buzzfuzz:export' %}">Export</a>
{% endblock %}